# Generated by Django 5.0.6 on 2025-01-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manager_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='BlazerMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleeves', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shoulder', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blazer_measurements', to='management.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blazer_measurements', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='KurtaMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleeves', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daman', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurta_measurements', to='management.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurta_measurements', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PantMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fog', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thighs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('knee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pant_measurements', to='management.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pant_measurements', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleeves', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('front', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirt_measurements', to='management.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirt_measurements', to='management.employee')),
            ],
        ),
    ]
